version: 2.1
orbs:
  node: circleci/node@4.1.0
  
jobs:
  build:
    docker:
        - image: circleci/node:12.14.0    
    steps:
        - checkout
        - run:
            npm i cordova && cd AppiumTest/ && cordova platform add android
#         - run:
#             command: curl -u "nimeshbhatt2:f8roo18EznR2cyEc59mt" -X POST "https://api-cloud.browserstack.com/app-automate/upload" -F "url=https://www.dropbox.com/s/5mpeu9i3naspzv2/app-debug.apk?dl=1" -F "data={\"custom_id\":\"MyApp\"}"
#         - run:
#             npx wdio conf/android_BS.conf.js
#   build_project:
#     docker:
#         - image: circleci/node:12.14.0
#     steps:
#         - checkout
#         - run:
#             cd AppiumTest/ && cordova platform add android
#         - run: 
#             cd AppiumTest/ && ls
# workflows:
#   node-tests:
#     jobs:
#       - build_test
#       - build_project:
#             requires:
#                 - build_test
