version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
    build:
        docker: 
            - image: circleci/node:7.10
        steps:
            - run:
                npm i
            - checkout:
                path: ~/AppiumTest
            - run:
                cordova platform add android
                cordova build android
            - checkout: 
                path: ~/yoyo
            - run:
                npx wdio conf/android_BS.conf.js

