version: 2.1
orbs:
  node: circleci/node@4.1.0
  
jobs:
  build:
    docker:
        - image: circleci/node:12.14.0    
    steps:
        - checkout
        - run:
            cd AppiumTest/ && ls
#   build_project:
#     docker:
#         - image: circleci/node:12.14.0
#     working_directory: ~/AppiumTest
#     steps:
#         - checkout
#         - run:
#             ls
# workflows:
#   node-tests:
#     jobs:
#       - build_test
#       - build_project:
#             requires:
#                 - build_test
